### ISSUE TITLE
Chat eating letters

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#17]
**Hello!**

It seems that sometimes the chat eats half of a letter that is close to the scrollbar. No error text.

![WoWScrnShot_032120_153143](https://user-images.githubusercontent.com/60573947/77349206-b7180180-6d4b-11ea-88db-578f046891d2.png)

Thanks :)

**Comment by Xruptor** [comment]
Yeah that's called chat trimming.  It's part of the blizzard framework.  When a link or word is too big to fit, it invokes a trimming function on the text to fit in the chat frame.  This is done by auto-sizing the string size. (String being the complete sentence as one singular object).  Sadly, sometimes this isn't always 100% exact and you get improper cropping of the characters at the edge of the frame.  Which is what you are getting in that picture.

The simplest solution is to find a "sweet spot" in the chat frame size.  Next time that happens, resize the chat frame by dragging the edge so that the words properly crop to the other side of the frame.  If you do it just right it usually prevents that from happening in the future.  This partially happens in irregular chat window sizes or extremely long text.  Which I'm seeing in your pic is one REALLY long link.

NOTE: If you have used the locked settings of xanChat, you may want to turn that off before resizing.  Otherwise the position and size of the chat will not be saved to the DB.

Hope this helps :D  BTW I love that you provide pictures. It helps tremendously!  I wish I had more issue bug trackers like you.

**Comment by Natlyz** [comment]
Aha, I see. I'll try to resize the chat.

Thanks, I like bug-tracking addons that I use.
