### ISSUE TITLE
Random copy malfunction.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#18]
**Hello!**

I'm randomly experiencing this "bug" that won't allow me to properly copy the text I want. No error text.

![WoWScrnShot_030320_150246](https://user-images.githubusercontent.com/60573947/77430605-7f14cb00-6dec-11ea-8bc1-2239fb71fb77.png)

Thanks :)

**Comment by Xruptor** [comment]
Can you give me a few more details?  What is preventing you from copying?  Can you describe using your picture?  On my end it just seems like the copy frame is working properly.

**Comment by Natlyz** [comment]
Please, compare my screenshot to how it normally looks. It won't allow me to properly choose the text I want to copy. This happened like 3-4 times in the recent week.

**Comment by Xruptor** [comment]
I think I know what it is.  Character limit or something in highlighting or copying stuff.  I guess after awhile too much text is put into it and it cannot select after a certain point.  I'll have to research this.

**Comment by Natlyz** [comment]
Is it possible to make it store only certain amount of most recent lines of text?

**Comment by Xruptor** [comment]
> Is it possible to make it store only certain amount of most recent lines of text?

Yep that's what I'm doing.  I'm adding pages to the copy chat function.  There is a hard limit of 500 lines for highlighting.  So I'll just show the most recent lines and if you want to go further back, then use the page back and forward buttons.

**Comment by Xruptor** [comment]
After some more testing it looks like it's not just the character limit but specific chat images that cause it to break.  Things like the currency icons or player role icons and such in chat that transfer over to the copy chat window.  It messes up the character limit because those are actually special image inserts.  So I removed them as well with the copy chat window.  Since you can't really copy and paste those anyways.  It looks like the pages is working with a chat line limit of 500 lines or less.  I'm still testing though.

**Comment by Xruptor** [comment]
I think I got it down.  I found some other bugs with player links and BNET links in chat.  It does not like copy and paste LOL.  Would cause all sort of issues.  So I've filtered them out so that the links are removed but the text remains.  Seems to be working.  The other issue is the scrolling.  You see since this is an editable box it functions differently then lets say your chat frame.  Scrolling is based on the cursor position and since you can't use your cursor on the chat frame it works differently.  This requires me to have to be creative on moving the scrollbar with the cursor to the bottom of the frame.  It seems to be working pretty good though.  If everything checks out, I'll release it today.

**Comment by Natlyz** [comment]
Can't wait to test it and find more bugs!

**Comment by Xruptor** [comment]
> Can't wait to test it and find more bugs!

Well there is one thing I'd like to point out before you post a bug report on it 😆 .  By default when you open the copy chat frame it will show the last 500 lines, **regardless** of the current **highest** page number.  It will **always show** the last 500 lines when you open the copy chat frame.

This is different when changing the pages.
So if you go back and forth in pages it may show 500 lines in the first page and only 10 in the second page.  This is normal behavior.  Because you are cycling through the amount of pages.  Otherwise if you didn't use the pages back and forward button, the copy frame will **always show** the last 500 lines.

I did this to make it quick to grab a copy chat without having to flip through the pages, especially if lets say the current page only has 10 lines.

I just wanted to say that ahead of time heh.

**Comment by Xruptor** [comment]
Oh and the scrollbar is a buggy mess of code on blizzards part.  So it's not 100% accurate and sometimes won't show all the way at the bottom.  But even though it's not at the bottom, trust me you will see the last text at the very bottom of the edit box copy frame.  I'm trying to force it to go to the bottom but it hates me sometimes.

**Comment by Natlyz** [comment]
Thanks! The new copy window looks nice, can't wait for it to bug so I could report it 😅
