### ISSUE TITLE
Focus!

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#23]
Hello! I'm back with another bug 😊

_2x [ADDON_ACTION_FORBIDDEN] AddOn 'XanChat' tried to call the protected function 'FocusUnit()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]:"]: in function 'FocusUnit'
[string "@FrameXML\ChatFrame.lua"]:1450: in function '?'
[string "@FrameXML\ChatFrame.lua"]:4839: in function 'ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4523: in function 'ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4559: in function 'ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>_

This popped up when I typed /focus in chat, but after relog everythng was fine.

Thanks!

**Comment by Xruptor** [comment]
This is a taint issue associated with any addon you may have installed.  The /focus command cannot be used by an addon as it's restricted to just macros.  It's been protected by Blizzard.

Also taint issues or protected functions can be caused by blamed on an addon even if the addon didn't trigger it (meaning another addon caused it).  It's a known issue with how Blizzard handles taints.  Its possible it could have been another completely different addon but because the addon that got blamed was the last one to execute at that precise moment, it gets blamed.  XanChat doesn't have any code that has to do with focus.

For more information how terrible the Blizzard taint and protected system is, please visit this site 😄 
[https://defectivetanking.wordpress.com/2014/01/18/wows-taint-system-addons-and-why-classic-was-so-much-easier/](https://defectivetanking.wordpress.com/2014/01/18/wows-taint-system-addons-and-why-classic-was-so-much-easier/)

**Comment by Natlyz** [comment]
I see. Well, I'll be back with another bug soon, I'm sure!

**Comment by Xruptor** [comment]
No problem! Sadly Blizzard's taint system is completely broken and it blames all sorts of addons indirectly even if they didn't trigger it. It's been an issue with addons for ages now for as long as I can remember. Most people nowadays just disable taint log and disable taint stuff in their bug swatter addons.

Even ElvUI and TukUI suffer from this problem lol.
[https://www.tukui.org/forum/viewtopic.php?t=9344](https://www.tukui.org/forum/viewtopic.php?t=9344)
