### ISSUE TITLE
Minor fixes.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#26]
Hello!

1. Maybe it's a minor thing, but the colour in the edit box isn't the same as the custom /w colour.
![WoWScrnShot_060720_225702](https://user-images.githubusercontent.com/60573947/83978973-c999e400-a913-11ea-8b82-a1c30ad13cda.png)
2. Locked settings don't get greyed out anymore.
![5353r](https://user-images.githubusercontent.com/60573947/83978997-e6361c00-a913-11ea-9377-ac1f806740e4.png)
3. Would be nice to be able to lock settings while in "additional settings" menu.

Thanks 😊

**Comment by Xruptor** [comment]
I fixed the locked settings not properly working.

Due to restrictions, I cannot edit the color of the text in the EditBox to match the color of the chat frame text.  This is because the EditBox pulls the color of the default whisper color and not the outgoing color. I cannot change this without causing some sort of taint issues. Sorry about that.

**Comment by Natlyz** [comment]
Thanks for the fix :)
