### ISSUE TITLE
Suggestion: class coloured names in chat.

### ISSUE THREAD

**Issue by Natlyz** [Xruptor/XanChat#6]
Hello!

I'd like to suggest a new option: class coloured names in chat will make easier to see when you, your firend or some guildie is being mentioned in chat when the name is differently coloured from the rest of the text.

![WoWScrnShot_020120_195204](https://user-images.githubusercontent.com/60573947/74723905-77da2a80-524c-11ea-91ac-24c08e4aa497.png)
_Something like that._

Thanks for this addon :)

**Comment by Xruptor** [comment]
Hello!  Class colors should be on by default with xanChat.  It's included with the addon.  If they didn't turn on for you then that's a bug I would need to look into.  Unless you meant something else?

**Comment by Natlyz** [comment]
Yeah, class colours work for name in **[120: Name]** but not in messages.

I meant class colour in messages for Names when somone mentions a character in chat, like in the screenshot I posted.

**Comment by Xruptor** [comment]
> Yeah, class colours work for name in **[120: Name]** but not in messages.
> 
> I meant class colour in messages for Names when someone mentions a character in chat, like in the screenshot I posted.

Oh okay.  That will require some chat parsing.  I believe this will only work with guild members and folks in a party or raid.  I don't think it will properly work with folks in trade and such.  I'll take a look.

**Comment by Natlyz** [comment]
Nice, thanks!

**Comment by Xruptor** [comment]
> Nice, thanks!

I've made some progress on this but I'm going to put it on hold until I can fix the issue in #7 .  If there is a parsing or filtering issue it needs to be resolved first, otherwise it may conflict with any additions I make on this request.

**Comment by Xruptor** [comment]
Okay so I fixed the other issue so I can get back to this one again :)

**Comment by Xruptor** [comment]
Alright I was able to add the player name color and level to the player brackets [].  However names used IN chat actually are a bit more complicated.  This is because it's treated differently depending on language/localization.  For example we just say "Bob was kicked from group."  but in other languages it's "Jane kicked Bob from group."  This leads to a lot of complications I just don't want to deal with honestly.

So as an alternative, what I'm going to do is colorize ANYTIME a person's name is mentioned in chat regardless of the sentence.  Yes that means if you type it yourself it will also be colorized in chat.

Note: This will only work with friends, guild, raid, party members.  It will not work for anyone whom you don't actually know.  I hope this suffices.  I'm really going out of my way to implement this as it's not something I really use.  However, I really want you to be happy with the addon so I'm going to implement it best I can.

**Comment by Natlyz** [comment]
Thanks, can't wait to test it :)
